---
- name: check postfix status
  hosts: web
  tasks:

  - name: check_postfix
    ansible.builtin.shell:
       cmd: systemctl status postfix 
    register: result

  - name: Display result
    debug:
      msg: "{{result.stdout_lines}}"
  
