---
- hosts: web
  become: yes
  become_method: sudo
  tasks:

  - name: stop postfix service
    yum:
      name: postfix
      state: latest
      update_cache: yes
    notify: stop postfix

  handlers:

  - name: stop postfix
    service:
      name: postfix 
      state: stopped 
      
  - name: Install nfs-utils
    yum: 
      name: nfs
      state: latest 
      update_cache: yes
    notify: start nfs
    
  handlers:
  
  - name: start nfs 
    service:
      name: nfs
      state: started       
