---
- hosts: web 
  tasks:

  - name: uninstall postfix 
    yum:
     name: postfix 
     state: latest
     update_cache: yes
   notify: stop postfix

  handlers:

  - name: stop postfix 
    service:
      name: postfix 
      state: stopped
