---
- hosts: web
  become: yes
  become_method: sudo
  tasks:

  - name: postfix service
    yum:
      name: postfix
      state: latest
      update_cache: yes
    notify: start postfix

  handlers:

  - name: start postfix
    service:
      name: postfix 
      state: started 
     
