---
- hosts: web 
  become: yes
  become_method: sudo 
  tasks:

  - name: Install postfix 
    yum:
     name: postfix 
     state: latest 
     update_cache: yes


  - name: start postfix
    service:
      name: postfix 
      state: started 
      