---
- hosts: web 
  become: yes
  become_method: sudo 
  tasks:

  - name: stop postfix service 
    service:
      name: postfix 
      state: stopped

  - name: uninstall postfix 
    yum:
     name: postfix 
     state: stopped 

  